apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
type: Opaque
data:
  # base64-encoded values
  db_root_password: REPLACE_WITH_BASE64
  db_user: REPLACE_WITH_BASE64
  db_password: REPLACE_WITH_BASE64
